### ISSUE TITLE
Params in URL

### ISSUE THREAD

**Issue by thomasschiet** [rawrmaan/restyped-axios#2]
In the [specification](https://github.com/rawrmaan/restyped#specification) I found the following:
> params: Route params in the URL (e.g. /users/:id would have id as a param)

However, it this does not work. The following code will call `/users/:id`, instead of `/users/1`.
```ts
client.request({
  url: '/users/:id',
  params: {
    id: 1,
  },
});
```
It seems like I also cannot change the `url` to `/users/1`, as it will expect `/users/:id`, even when using `client.request<'/users/:id'>`.

**Comment by rawrmaan** [comment]
You should be able to change the `url` to `/users/1` if you use `client.request<'/users/:id'>`. Have you actually tried this?

**Comment by wolever** [comment]
Would you consider a PR that allows you to use something broadly similar to: `client.get('/users/:id', { id: 42 })`

This would also be nice because the thing which expands `'/users/:id'` to `'/users/42'` could also perform the appropriate escaping on the parameters.

**Comment by rawrmaan** [comment]
I agree that it would be nice, but unfortunately adding logic like that would break the core RESTyped principle of "it's just types".

Currently you can do the following, which gets close to the syntax you're looking for:

```typescript
client.get<'/users/:id'>('/users/42')
```

**Comment by wolever** [comment]
Ah gotcha - because even though it would be straightforward from a type safety perspective, it would require additional runtime code.
