### ISSUE TITLE
Retry support

### ISSUE THREAD

**Issue by kshmir** [rawrmaan/restyped-axios#6]
We're starting to use axios with restyped, it seems pretty cool!

Our only concern was the lack of retry policy.

https://github.com/softonic/axios-retry Seems like an option to be used with this library.

We'll try it down the road, would you consider incorporating such a thing or should we wrap this library with retry support?

Cheers!

**Comment by rawrmaan** [comment]
This should work just fine with this library. This library is just a wrapper around normal axios that doesn't, and will not, add any extra runtime functionality. Thanks for giving `restyped-axios` a try!
